### ISSUE TITLE
Fix: PUT `groups/{groupId}/?Action=generateInvitationLink` returns Error

### ISSUE THREAD

**Issue by taniguchiiqqq** [genesis-tech-tribe/nishiki-backend#293]
## Bug Description
When you call PUT `groups/{groupId}/?Action=generateInvitationLink`, you got Iternal Server Error.
This is the error message in CloudWatch.
```
2024-02-13T18:50:13.251Z	48f6944a-5fb7-42dd-a269-487514feb460	ERROR	SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:4747:19)
    at successSteps (node:internal/deps/undici/undici:4718:27)
    at specConsumeBody (node:internal/deps/undici/undici:4724:9)
    at _Request.json (node:internal/deps/undici/undici:4614:18)
    at HonoRequest.cachedBody (/var/task/index.js:5962:40)
    at HonoRequest.json (/var/task/index.js:6021:17)
    at /var/task/index.js:10109:14
    at dispatch (/var/task/index.js:5851:23)
    at /var/task/index.js:5852:20
```

## Expected Behavior

`groups/{groupId}/?Action=generateInvitationLink`, return invitationLink

**Comment by hitohata** [comment]
It seems this error occurs in the router. Can you get the body of the request?
Or do you have any idea how to resolve this problem?

**Comment by taniguchiiqqq** [comment]
@hitohata 
Yes, I found `c.req.json(),` occurred the error because it doesn't have body data when the Action is generateInvitationLink. I'll fix it soon

**Comment by hitohata** [comment]
OK. I've made sense. I didn't know if the body was not provided, this error would occur. I feel like I really learned something today. Thank you.
